version: '3.9'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile  
    #image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      #- ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./wordpress:/var/www/html:delegated
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./wordpress:/var/www/html:delegated

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:8081"
    ports:
     # - "80:80"
      - "8081:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.wordpress-docker.test`)"
      - "traefik.http.routers.whoami.entrypoints=web"      


  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000




  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock


  # portainer:
  #   image: portainer/portainer
  #   command: -H unix:///var/run/docker.sock
  #   restart: always
  #   ports:
  #     - 9000:9000
  #     - 8800:8000
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     #- portainer_data:/data


  # portainer_data:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: /Users/edwardconcepcion/Applications/MAMP/htdocs/DockerStack/portainer      